FROM postgres:9.2

ENV POSTGRES_DB crashrec
ENV POSTGRES_USER crashrec
ENV POSTGRES_PASSWORD crashrec

COPY psql_init.sql /docker-entrypoint-initdb.d/
COPY change-postgresql.conf.sh /docker-entrypoint-initdb.d/

