
-- ALTER SYSTEM SET max_prepared_transactions = 50;

CREATE TABLE TABLE1 (
    id SERIAL PRIMARY KEY,
    NODE_NAME VARCHAR(100),
    RANDOM INTEGER
);

CREATE TABLE TABLE2 (
    id SERIAL PRIMARY KEY,
    VALUE INTEGER
);

